-- SALES DATA ANALYSIS PROJECT 
-- TOOL: SQL
-- DATASET: sales_data.sales_data

USE SALES_DATA;
-- 1.  OVERALL SALES PERFORMANCE
SELECT COUNT(*) AS TOTAL_TRANSACTION,
SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY_SOLD,
ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES,
ROUND(AVG(SALES_AMOUNT),2) AS AVERAGE_TRANSACTION
FROM sales_data.sales_data;

-- 2.  MONTHLY SALES PERFORMANCE
SELECT substring_index(SALE_DATE, '/', 1) AS MONTHS, ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES
FROM sales_data.sales_data
group by substring_index(SALE_DATE, '/', 1) 
order by CAST(MONTHS AS unsigned);

-- 3.  PRODUCT CATEGORY PERFORMANCE
SELECT PRODUCT_CATEGORY, SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY, ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES
FROM sales_data.sales_data
group by PRODUCT_CATEGORY
ORDER BY TOTAL_SALES DESC;

-- 4.  CUSTOMER TYPE PERFORMANCE
SELECT Customer_Type, ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES, COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Customer_Type
ORDER BY TOTAL_SALES DESC;

-- 5.  SALES REP PERFORMANCE
SELECT Sales_Rep, ROUND(AVG(SALES_AMOUNT),2) AS AVERAGE_TRANSACTION,ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES,
COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Sales_Rep
ORDER BY TOTAL_SALES DESC;

-- 6.  REGIONAL PERFORMANCE
SELECT Region, ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES, COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Region
ORDER BY TOTAL_SALES DESC;

-- 7.  SALES CHANNEL PERFORMANCE
SELECT Sales_Channel, ROUND(AVG(SALES_AMOUNT),2) AS AVERAGE_TRANSACTION,ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES,
COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Sales_Channel
ORDER BY TOTAL_SALES DESC;

-- 8.  PAYMENT METHOD PERFORMANCE
SELECT Payment_Method, ROUND(AVG(SALES_AMOUNT),2) AS AVERAGE_TRANSACTION,ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES,
COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Payment_Method
ORDER BY TOTAL_SALES DESC;

-- 9.  HIGH VS LOW SALES
SELECT
CASE
WHEN SALES_AMOUNT >= 5000 THEN 'HIGH_SALES'
ELSE 'LOW_SALES'
END AS SALES_LEVEL,
COUNT(*) AS TOTAL_TRANSACTION, ROUND(SUM(Sales_Amount),2) AS TOTAL_SALES
FROM sales_data.sales_data
GROUP BY SALES_LEVEL
ORDER BY TOTAL_SALES;

--   SALES REP + PERFORMANCE FILTER
--      THIS ONE WILL IDENTIFY REPS WHO GENERATED MORE THAN ₦1 MILLION IN SALES AND HANDELED MORE THAN 200 TRANSACTION
-- 10.  TOP SALES REP PERFORMANCE
SELECT SALES_REP, ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_SALES, COUNT(*) AS TOTAL_TRANSACTION
FROM sales_data.sales_data
GROUP BY Sales_Rep
HAVING TOTAL_SALES >1000000 AND TOTAL_TRANSACTION > 200
ORDER BY TOTAL_SALES DESC;

-- 11.  AVERAGE MONTHLY SALES
SELECT ROUND(AVG(TOTAL_SALES),2) AS AVERAGE_MONTHLY_SALES 
FROM (SELECT substring_index(SALE_DATE, '/', 1) AS MONTHS, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM sales_data.sales_data
group by substring_index(SALE_DATE, '/', 1) ) AS MONTHLY_TOTALS;